name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: 'out/github-contribution-grid-snake.svg'
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake animation"
          branch: main
          file_pattern: 'out/github-contribution-grid-snake.svg'